export default {
    area: [
        { id: -1, value: "全部", },
        { id: 7, value: "华语", },
        { id: 96, value: "欧美", },
        { id: 8, value: "日本", },
        { id: 16, value: "韩国", },
        { id: 0, value: "其他", },
    ],
    type: [
        { id: -1, value: "全部", },
        { id: 1, value: "男歌手", },
        { id: 2, value: "女歌手", },
        { id: 3, value: "乐队", },
    ],
    initial: [
        { id: "-1", value: "全部", },
        { id: "a", value: "a", },
        { id: "b", value: "b", },
        { id: "c", value: "c", },
        { id: "d", value: "d", },
        { id: "e", value: "e", },
        { id: "f", value: "f", },
        { id: "g", value: "g", },
        { id: "h", value: "h", },
        { id: "i", value: "i", },
        { id: "j", value: "j", },
        { id: "k", value: "k", },
        { id: "l", value: "l", },
        { id: "m", value: "m", },
        { id: "n", value: "n", },
        { id: "o", value: "o", },
        { id: "p", value: "p", },
        { id: "q", value: "q", },
        { id: "r", value: "r", },
        { id: "s", value: "s", },
        { id: "t", value: "t", },
        { id: "u", value: "u", },
        { id: "v", value: "v", },
        { id: "w", value: "w", },
        { id: "x", value: "x", },
        { id: "y", value: "y", },
        { id: "z", value: "z", },
        { id: '0', value: '#' }
    ],
};
